{% set name = "pysciencemode" %}
{% set version = "1.1.5" %}
{% set python_min = "3.10" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pysciencemode-{{ version }}.tar.gz
  sha256: 06557e593cfc52d064e6a7a75a40921d1ca2c3e6a06f0a4275ee8102c5793964

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - crccheck
    - colorama
    - pyserial


test:
  imports:
    - pysciencemode
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
about:
  home: "https://github.com/s2mLab/pyScienceMode"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Python interface to control the Rehastim2 and RehastimP24 devices."
  doc_url: https://github.com/s2mLab/pyScienceMode/blob/master/README.md
  dev_url: https://github.com/s2mLab/pyScienceMode

extra:
  recipe-maintainers:
    - Kev1CO
